apiVersion: v1
kind: Pod
metadata:
  name: sgx-isin
spec:
  containers:
  - image: sgx-isin:v1
    name: sgx-isin
    volumeMounts:
      - mountPath: /test-pd
        name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /datax
      type: DirectoryOrCreate